### ISSUE TITLE
asap_set_compile_options arguments to swift_set_compile_options

### ISSUE THREAD

**Issue by KammutierSpule** [abdes/asap#24]
It looks that the arguments are not passed to swift_set_compile_options

There is some issue while (not) passing the WARNING.

I'm trying to understand the problem, I will give more details if I found it the exact problem.

**Comment by KammutierSpule** [comment]
On the function asap_add_executable
it calls swift_add_executable and arguments are passed ok.
but then it calls asap_set_compile_definitions but arguments are not passed.
So the -Werror will be set even if the WARNING was used.

**Comment by abdes** [comment]
Can you please take a look at issue #21? This looks like a duplicate.

**Comment by KammutierSpule** [comment]
Yes, I believe so :)

I was using an outdated version.
